In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Read in the dataset
listings_df=pd.read_csv('listings.csv')
listings_df.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,5269,https://www.airbnb.com/rooms/5269,20220608163112,2022-06-08,Upcountry Hospitality in the 'Auwai Suite,"The 'Auwai Suite is a lovely, self-contained a...","We are located on the ""sunny side"" of Waimea, ...",https://a0.muscache.com/pictures/5b52b72f-5a09...,7620,https://www.airbnb.com/users/show/7620,...,4.89,5.00,4.78,119-269-5808-01R,f,3,3,0,0,0.14
1,157141,https://www.airbnb.com/rooms/157141,20220608163112,2022-06-08,Hawaii Condo ON THE BEACH! Sleeps 4,<b>The space</b><br />ALOHA! ALOHA! ALOHA!<br ...,Located just 16 miles from famous Shark's Cove...,https://a0.muscache.com/pictures/10178068/a57c...,754830,https://www.airbnb.com/users/show/754830,...,4.91,4.66,4.64,NaN,f,1,1,0,0,2.53
2,162600,https://www.airbnb.com/rooms/162600,20220608163112,2022-06-09,Waipouli Beach Resort A402 Prime ocean front ...,At the forefront of East Shore accommodation i...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,756093,https://www.airbnb.com/users/show/756093,...,4.89,5.00,4.74,430080010022,f,80,80,0,0,0.21
3,620423234449702127,https://www.airbnb.com/rooms/620423234449702127,20220608163112,2022-06-08,Tropical Hauula Hideaway w/ ocean & mountain v...,This property is a legally established dwellin...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,457470945,https://www.airbnb.com/users/show/457470945,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
4,342351,https://www.airbnb.com/rooms/342351,20220608163112,2022-06-08,Honaunau Farm Retreat - Garden Cottage,Honaunau Farm Wellness Retreat is a 7 acre org...,"We are located in a rural, tropical agricultur...",https://a0.muscache.com/pictures/miso/Hosting-...,283136,https://www.airbnb.com/users/show/283136,...,4.85,4.94,4.79,NaN,f,4,4,0,0,0.80

In [2]:
host=listings_df[['host_url','host_since','host_location','host_about','host_response_time','host_response_rate','host_is_superhost']]
host.head()

,host_url,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost
0,https://www.airbnb.com/users/show/7620,2009-02-09,"Waimea, Hawaii, United States","Lea, born and raised on the Island of Hawaii, ...",within a few hours,100%,t
1,https://www.airbnb.com/users/show/754830,2011-06-28,"San Jose, California, United States","Couple from San Jose, CA who enjoys traveling!",within a day,100%,f
2,https://www.airbnb.com/users/show/756093,2011-06-28,"Lihue, Hawaii, United States",Kauai Exclusive Management. A locally owned an...,within a few hours,96%,f
3,https://www.airbnb.com/users/show/457470945,2022-05-04,US,NaN,within a few hours,100%,f
4,https://www.airbnb.com/users/show/283136,2010-11-10,"Kealakekua, Hawaii, United States",Honaunau Farm Wellness Retreat is a place wher...,within a few hours,100%,t

In [3]:
neighborhood=listings_df[['neighbourhood','neighbourhood_cleansed','neighbourhood_group_cleansed']]
neighborhood.head()

,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed
0,"Kamuela, Hawaii, United States",South Kohala,Hawaii
1,"Punaluu, Hawaii, United States",Koolauloa,Honolulu
2,NaN,Kapaa-Wailua,Kauai
3,NaN,Koolauloa,Honolulu
4,"Captain Cook, Hawaii, United States",South Kona,Hawaii

In [4]:
nights=listings_df[['minimum_nights','maximum_nights','minimum_minimum_nights','maximum_minimum_nights','minimum_maximum_nights','maximum_maximum_nights','minimum_nights_avg_ntm','maximum_nights_avg_ntm','calendar_updated']]
nights.head()

,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated
0,5,1125,5,5,1125,1125,5.0,1125.0,NaN
1,2,21,2,2,21,21,2.0,21.0,NaN
2,1,1125,3,3,1125,1125,3.0,1125.0,NaN
3,10,365,10,10,365,365,10.0,365.0,NaN
4,4,1125,2,4,1125,1125,4.0,1125.0,NaN

In [5]:
availability=listings_df[['id','has_availability','availability_30','availability_60','availability_90','availability_365']]
availability.head()

,id,has_availability,availability_30,availability_60,availability_90,availability_365
0,5269,t,6,6,6,121
1,157141,t,0,0,0,0
2,162600,t,1,4,17,107
3,620423234449702127,t,10,10,38,301
4,342351,t,3,6,13,234

In [6]:
cleaned_listings_df=listings_df[['id','listing_url','neighbourhood_cleansed','neighbourhood_group_cleansed','latitude','longitude','room_type','bathrooms','bathrooms_text','bedrooms','beds','amenities','price','minimum_nights','maximum_nights','calendar_updated','has_availability','availability_30','availability_60','availability_90','availability_365','number_of_reviews','number_of_reviews_ltm','number_of_reviews_l30d','review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value','instant_bookable','reviews_per_month']]
cleaned_listings_df

,id,listing_url,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,room_type,bathrooms,bathrooms_text,bedrooms,...,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month
0,5269,https://www.airbnb.com/rooms/5269,South Kohala,Hawaii,20.027400,-155.702000,Entire home/apt,NaN,1 bath,1.0,...,0,4.56,4.78,4.33,5.00,4.89,5.00,4.78,f,0.14
1,157141,https://www.airbnb.com/rooms/157141,Koolauloa,Honolulu,21.589890,-157.891540,Entire home/apt,NaN,1 bath,1.0,...,0,4.54,4.64,4.62,4.84,4.91,4.66,4.64,f,2.53
2,162600,https://www.airbnb.com/rooms/162600,Kapaa-Wailua,Kauai,22.061740,-159.320520,Entire home/apt,NaN,3 baths,2.0,...,0,4.95,4.95,4.89,4.95,4.89,5.00,4.74,f,0.21
3,620423234449702127,https://www.airbnb.com/rooms/620423234449702127,Koolauloa,Honolulu,21.604002,-157.895791,Entire home/apt,NaN,2 baths,3.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN
4,342351,https://www.airbnb.com/rooms/342351,South Kona,Hawaii,19.450730,-155.872810,Entire home/apt,NaN,1 bath,1.0,...,4,4.82,4.86,4.76,4.76,4.85,4.94,4.79,f,0.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26340,48594067,https://www.airbnb.com/rooms/48594067,North Shore Kauai,Kauai,22.226800,-159.471720,Private room,NaN,1 private bath,1.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN
26341,52957220,https://www.airbnb.com/rooms/52957220,North Shore Oahu,Honolulu,21.590430,-158.111510,Entire home/apt,NaN,2 baths,1.0,...,0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,t,0.40
26342,6250197,https://www.airbnb.com/rooms/6250197,Koolauloa,Honolulu,21.650280,-157.913180,Entire home/apt,NaN,1 bath,2.0,...,1,4.97,4.94,4.89,4.97,5.00,4.94,4.87,f,1.28
26343,612967674562055271,https://www.airbnb.com/rooms/612967674562055271,Lanai,Maui,20.939219,-156.939224,Entire home/apt,NaN,2 baths,2.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN
26344,32338874,https://www.airbnb.com/rooms/32338874,Primary Urban Center,Honolulu,21.283690,-157.839470,Entire home/apt,NaN,1 bath,1.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN

In [7]:
cleaned_listings_df=cleaned_listings_df.dropna(axis=1, how='all')
cleaned_listings_df

,id,listing_url,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,room_type,bathrooms_text,bedrooms,beds,...,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month
0,5269,https://www.airbnb.com/rooms/5269,South Kohala,Hawaii,20.027400,-155.702000,Entire home/apt,1 bath,1.0,1.0,...,0,4.56,4.78,4.33,5.00,4.89,5.00,4.78,f,0.14
1,157141,https://www.airbnb.com/rooms/157141,Koolauloa,Honolulu,21.589890,-157.891540,Entire home/apt,1 bath,1.0,2.0,...,0,4.54,4.64,4.62,4.84,4.91,4.66,4.64,f,2.53
2,162600,https://www.airbnb.com/rooms/162600,Kapaa-Wailua,Kauai,22.061740,-159.320520,Entire home/apt,3 baths,2.0,3.0,...,0,4.95,4.95,4.89,4.95,4.89,5.00,4.74,f,0.21
3,620423234449702127,https://www.airbnb.com/rooms/620423234449702127,Koolauloa,Honolulu,21.604002,-157.895791,Entire home/apt,2 baths,3.0,5.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN
4,342351,https://www.airbnb.com/rooms/342351,South Kona,Hawaii,19.450730,-155.872810,Entire home/apt,1 bath,1.0,1.0,...,4,4.82,4.86,4.76,4.76,4.85,4.94,4.79,f,0.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26340,48594067,https://www.airbnb.com/rooms/48594067,North Shore Kauai,Kauai,22.226800,-159.471720,Private room,1 private bath,1.0,1.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN
26341,52957220,https://www.airbnb.com/rooms/52957220,North Shore Oahu,Honolulu,21.590430,-158.111510,Entire home/apt,2 baths,1.0,2.0,...,0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,t,0.40
26342,6250197,https://www.airbnb.com/rooms/6250197,Koolauloa,Honolulu,21.650280,-157.913180,Entire home/apt,1 bath,2.0,2.0,...,1,4.97,4.94,4.89,4.97,5.00,4.94,4.87,f,1.28
26343,612967674562055271,https://www.airbnb.com/rooms/612967674562055271,Lanai,Maui,20.939219,-156.939224,Entire home/apt,2 baths,2.0,4.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN
26344,32338874,https://www.airbnb.com/rooms/32338874,Primary Urban Center,Honolulu,21.283690,-157.839470,Entire home/apt,1 bath,1.0,2.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN

In [8]:
cleaned_listings_df=cleaned_listings_df.dropna(subset=['reviews_per_month'])
cleaned_listings_df

,id,listing_url,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,room_type,bathrooms_text,bedrooms,beds,...,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month
0,5269,https://www.airbnb.com/rooms/5269,South Kohala,Hawaii,20.02740,-155.70200,Entire home/apt,1 bath,1.0,1.0,...,0,4.56,4.78,4.33,5.00,4.89,5.00,4.78,f,0.14
1,157141,https://www.airbnb.com/rooms/157141,Koolauloa,Honolulu,21.58989,-157.89154,Entire home/apt,1 bath,1.0,2.0,...,0,4.54,4.64,4.62,4.84,4.91,4.66,4.64,f,2.53
2,162600,https://www.airbnb.com/rooms/162600,Kapaa-Wailua,Kauai,22.06174,-159.32052,Entire home/apt,3 baths,2.0,3.0,...,0,4.95,4.95,4.89,4.95,4.89,5.00,4.74,f,0.21
4,342351,https://www.airbnb.com/rooms/342351,South Kona,Hawaii,19.45073,-155.87281,Entire home/apt,1 bath,1.0,1.0,...,4,4.82,4.86,4.76,4.76,4.85,4.94,4.79,f,0.80
5,5387,https://www.airbnb.com/rooms/5387,South Kona,Hawaii,19.43081,-155.88069,Entire home/apt,1 bath,NaN,2.0,...,0,4.65,4.65,4.45,4.85,4.88,4.72,4.75,t,1.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26335,16770600,https://www.airbnb.com/rooms/16770600,Primary Urban Center,Honolulu,21.28364,-157.83954,Entire home/apt,1 bath,1.0,3.0,...,0,4.93,4.96,4.93,4.99,4.97,4.91,4.89,f,1.78
26337,28389238,https://www.airbnb.com/rooms/28389238,Kihei-Makena,Maui,20.79580,-156.50377,Entire home/apt,2 baths,2.0,4.0,...,0,5.00,5.00,5.00,5.00,5.00,5.00,4.83,t,0.34
26339,37755337,https://www.airbnb.com/rooms/37755337,North Shore Oahu,Honolulu,21.59340,-158.10430,Entire home/apt,1 bath,1.0,1.0,...,3,3.90,4.20,3.80,4.20,4.20,4.10,3.70,f,0.33
26341,52957220,https://www.airbnb.com/rooms/52957220,North Shore Oahu,Honolulu,21.59043,-158.11151,Entire home/apt,2 baths,1.0,2.0,...,0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,t,0.40
26342,6250197,https://www.airbnb.com/rooms/6250197,Koolauloa,Honolulu,21.65028,-157.91318,Entire home/apt,1 bath,2.0,2.0,...,1,4.97,4.94,4.89,4.97,5.00,4.94,4.87,f,1.28

In [9]:
cleaned_listings_df.nunique()

id                              21675
listing_url                     21675
neighbourhood_cleansed             30
neighbourhood_group_cleansed        4
latitude                        15976
longitude                       14955
room_type                           4
bathrooms_text                     34
bedrooms                           12
beds                               22
amenities                       18595
price                            1448
minimum_nights                     50
maximum_nights                    152
has_availability                    2
availability_30                    31
availability_60                    61
availability_90                    91
availability_365                  366
number_of_reviews                 417
number_of_reviews_ltm             157
number_of_reviews_l30d             25
review_scores_rating              146
review_scores_accuracy            147
review_scores_cleanliness         161
review_scores_checkin             126
review_scores_communication       142
review_scores_location            115
review_scores_value               150
instant_bookable                    2
reviews_per_month                 764
dtype: int64

In [10]:
cleaned_bathrooms=cleaned_listings_df['bathrooms_text'].unique()
cleaned_bathrooms

array(['1 bath', '3 baths', '2 baths', '1 private bath', '2.5 baths',
       '1.5 baths', '1.5 shared baths', '1 shared bath', '4 baths',
       '3.5 baths', '3.5 shared baths', 'Shared half-bath', '4.5 baths',
       '2 shared baths', '0 shared baths', 'Half-bath', '0 baths',
       '5.5 baths', '3 shared baths', nan, '5 baths', '8 baths',
       '6.5 baths', '6 baths', '7.5 baths', '7 baths', '4 shared baths',
       '10 baths', '2.5 shared baths', '8.5 baths', '9.5 baths',
       '14 baths', '4.5 shared baths', '11 baths', 'Private half-bath'],
      dtype=object)

In [11]:
cleaned_listings_df=cleaned_listings_df.replace('Private half-bath', 'Half-bath', regex=True)

cleaned_bathrooms=cleaned_listings_df['bathrooms_text'].unique()
cleaned_bathrooms

array(['1 bath', '3 baths', '2 baths', '1 private bath', '2.5 baths',
       '1.5 baths', '1.5 shared baths', '1 shared bath', '4 baths',
       '3.5 baths', '3.5 shared baths', 'Shared half-bath', '4.5 baths',
       '2 shared baths', '0 shared baths', 'Half-bath', '0 baths',
       '5.5 baths', '3 shared baths', nan, '5 baths', '8 baths',
       '6.5 baths', '6 baths', '7.5 baths', '7 baths', '4 shared baths',
       '10 baths', '2.5 shared baths', '8.5 baths', '9.5 baths',
       '14 baths', '4.5 shared baths', '11 baths'], dtype=object)

In [12]:
cleaned_listings_df=cleaned_listings_df.replace('0 shared baths', '0 baths', regex=True)

cleaned_bathrooms=cleaned_listings_df['bathrooms_text'].unique()
cleaned_bathrooms

array(['1 bath', '3 baths', '2 baths', '1 private bath', '2.5 baths',
       '1.5 baths', '1.5 shared baths', '1 shared bath', '4 baths',
       '3.5 baths', '3.5 shared baths', 'Shared half-bath', '4.5 baths',
       '2 shared baths', '0 baths', 'Half-bath', '5.5 baths',
       '3 shared baths', nan, '5 baths', '8 baths', '6.5 baths',
       '6 baths', '7.5 baths', '7 baths', '4 shared baths', '10 baths',
       '2.5 shared baths', '8.5 baths', '9.5 baths', '14 baths',
       '4.5 shared baths', '11 baths'], dtype=object)

In [13]:
cleaned_listings_df

,id,listing_url,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,room_type,bathrooms_text,bedrooms,beds,...,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month
0,5269,https://www.airbnb.com/rooms/5269,South Kohala,Hawaii,20.02740,-155.70200,Entire home/apt,1 bath,1.0,1.0,...,0,4.56,4.78,4.33,5.00,4.89,5.00,4.78,f,0.14
1,157141,https://www.airbnb.com/rooms/157141,Koolauloa,Honolulu,21.58989,-157.89154,Entire home/apt,1 bath,1.0,2.0,...,0,4.54,4.64,4.62,4.84,4.91,4.66,4.64,f,2.53
2,162600,https://www.airbnb.com/rooms/162600,Kapaa-Wailua,Kauai,22.06174,-159.32052,Entire home/apt,3 baths,2.0,3.0,...,0,4.95,4.95,4.89,4.95,4.89,5.00,4.74,f,0.21
4,342351,https://www.airbnb.com/rooms/342351,South Kona,Hawaii,19.45073,-155.87281,Entire home/apt,1 bath,1.0,1.0,...,4,4.82,4.86,4.76,4.76,4.85,4.94,4.79,f,0.80
5,5387,https://www.airbnb.com/rooms/5387,South Kona,Hawaii,19.43081,-155.88069,Entire home/apt,1 bath,NaN,2.0,...,0,4.65,4.65,4.45,4.85,4.88,4.72,4.75,t,1.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26335,16770600,https://www.airbnb.com/rooms/16770600,Primary Urban Center,Honolulu,21.28364,-157.83954,Entire home/apt,1 bath,1.0,3.0,...,0,4.93,4.96,4.93,4.99,4.97,4.91,4.89,f,1.78
26337,28389238,https://www.airbnb.com/rooms/28389238,Kihei-Makena,Maui,20.79580,-156.50377,Entire home/apt,2 baths,2.0,4.0,...,0,5.00,5.00,5.00,5.00,5.00,5.00,4.83,t,0.34
26339,37755337,https://www.airbnb.com/rooms/37755337,North Shore Oahu,Honolulu,21.59340,-158.10430,Entire home/apt,1 bath,1.0,1.0,...,3,3.90,4.20,3.80,4.20,4.20,4.10,3.70,f,0.33
26341,52957220,https://www.airbnb.com/rooms/52957220,North Shore Oahu,Honolulu,21.59043,-158.11151,Entire home/apt,2 baths,1.0,2.0,...,0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,t,0.40
26342,6250197,https://www.airbnb.com/rooms/6250197,Koolauloa,Honolulu,21.65028,-157.91318,Entire home/apt,1 bath,2.0,2.0,...,1,4.97,4.94,4.89,4.97,5.00,4.94,4.87,f,1.28

In [15]:
pricing_df=cleaned_listings_df[['id','price','neighbourhood_cleansed','neighbourhood_group_cleansed','room_type','bedrooms','review_scores_value']]
pricing_df.head()

,id,price,neighbourhood_cleansed,neighbourhood_group_cleansed,room_type,bedrooms,review_scores_value
0,5269,$140.00,South Kohala,Hawaii,Entire home/apt,1.0,4.78
1,157141,$130.00,Koolauloa,Honolulu,Entire home/apt,1.0,4.64
2,162600,$557.00,Kapaa-Wailua,Kauai,Entire home/apt,2.0,4.74
4,342351,$109.00,South Kona,Hawaii,Entire home/apt,1.0,4.79
5,5387,$90.00,South Kona,Hawaii,Entire home/apt,NaN,4.75

In [16]:
pricing_df=pricing_df.dropna()
pricing_df.head(10)

,id,price,neighbourhood_cleansed,neighbourhood_group_cleansed,room_type,bedrooms,review_scores_value
0,5269,$140.00,South Kohala,Hawaii,Entire home/apt,1.0,4.78
1,157141,$130.00,Koolauloa,Honolulu,Entire home/apt,1.0,4.64
2,162600,$557.00,Kapaa-Wailua,Kauai,Entire home/apt,2.0,4.74
4,342351,$109.00,South Kona,Hawaii,Entire home/apt,1.0,4.79
6,347803,$341.00,Lahaina,Maui,Entire home/apt,2.0,4.29
7,350658,$210.00,Kihei-Makena,Maui,Entire home/apt,1.0,4.82
8,164132,$756.00,Ewa,Honolulu,Entire home/apt,3.0,4.80
9,5389,$299.00,North Kona,Hawaii,Entire home/apt,3.0,4.77
10,164963,$500.00,North Shore Oahu,Honolulu,Entire home/apt,2.0,4.64
11,168169,$155.00,North Kona,Hawaii,Entire home/apt,2.0,4.59

In [21]:
pricing_df.dtypes

id                                int64
price                            object
neighbourhood_cleansed           object
neighbourhood_group_cleansed     object
room_type                        object
bedrooms                        float64
review_scores_value             float64
dtype: object

In [25]:
pricing_df['price_per_room']=pricing_df.price/pricing_df.bedrooms
pricing_df.head(10)

,id,price,neighbourhood_cleansed,neighbourhood_group_cleansed,room_type,bedrooms,review_scores_value,price_per_room
0,5269,140.0,South Kohala,Hawaii,Entire home/apt,1.0,4.78,140.000000
1,157141,130.0,Koolauloa,Honolulu,Entire home/apt,1.0,4.64,130.000000
2,162600,557.0,Kapaa-Wailua,Kauai,Entire home/apt,2.0,4.74,278.500000
4,342351,109.0,South Kona,Hawaii,Entire home/apt,1.0,4.79,109.000000
6,347803,341.0,Lahaina,Maui,Entire home/apt,2.0,4.29,170.500000
7,350658,210.0,Kihei-Makena,Maui,Entire home/apt,1.0,4.82,210.000000
8,164132,756.0,Ewa,Honolulu,Entire home/apt,3.0,4.80,252.000000
9,5389,299.0,North Kona,Hawaii,Entire home/apt,3.0,4.77,99.666667
10,164963,500.0,North Shore Oahu,Honolulu,Entire home/apt,2.0,4.64,250.000000
11,168169,155.0,North Kona,Hawaii,Entire home/apt,2.0,4.59,77.500000

In [42]:
import psycopg2

conn = psycopg2.connect(user='postgres',
                       password='postgres',
                       host='hawaii-airbnb.c5hzvxbldmyx.us-east-1.rds.amazonaws.com',
                       port='5432',
                       database='hawaii')

cur=conn.cursor()

sql='''CREATE TABLE pricing (id varchar NOT NULL,\
           price float NOT NULL,\
           neighbourhood_cleansed varchar NOT NULL,\
           neighbourhood_group_cleansed varchar NOT NULL,\
           room_type varchar NOT NULL,\
           bedrooms float NOT NULL,\
           review_scores_value float NOT NULL,\
           price_per_room float NOT NULL);'''

cur.execute(sql)

conn.commit()

conn.close()

In [44]:
pricing_df.to_csv('pricing.csv', encoding='utf-8', index=False)